services:
  grawards_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PYTHONPATH=.
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload